
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    # V 开头的只会执行一次，下次项目启动不会执行，也不可以修改原始文件，否则项目启动会报错，如果需要对 V 开头的脚本做修改，
    #如果有个 SQL 脚本需要在每次启动的时候都执行，那么将 V 改为 R 开头即可, flyway默认开启
#  flyway:
#    enabled: true
  #  因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
#  解决：在application.properties里配置
#  spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
hl:
  xx:
    age: 11
    telephone: 13833902567
xxx:
  xx: xuexi
server:
  port: 80